CREATE TABLE products (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  price DOUBLE NOT NULL,
  stock_quantity INT NOT NULL,
  image_path VARCHAR(255) NOT NULL
);