### DELETE product by id as JSON
DELETE http://localhost:8089/products/1
Accept: application/json

### DELETE product by id as XML
DELETE http://localhost:8089/products/12
Accept: application/xml

### DELETE product by id (error case with invalid id) as JSON
DELETE http://localhost:8089/products/100
Accept: application/json