ALTER TABLE products
    ADD category_id BIGINT NULL;

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL;

ALTER TABLE products
    DROP FOREIGN KEY FK_PRODUCTS_ON_CATEGORY;